---
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: alphaprime-2025
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - VERSION=docker
        #      - PLEX_CLAIM=claim-A8fZ-e1snXaq1YrowYkH
      - ADVERTISE_IP="http://10.0.0.11:32400/"
    volumes:
      - ./config:/config
      - /dev/shm/plex/transcode:/transcode
      - /mnt/storage/Plex/Videos:/mnt/storage/Plex/Videos
      - /mnt/storage/Videos:/mnt/storage/Videos
    ports:
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32400:32400/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped